spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hbm2ddl:
          import_files: import.sql
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    locations: classpath:db/migration