version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videostore
    logging:
      driver: "json-file"
      options:
        max-size: "20000k"
        max-file: "1"